# Site settings
title: Ecenur Öztürk
description: Ruby on Rails Developer
url: 'http://ecenurozturk.github.io'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Ecenur Öztürk'
  email: ecenurrozturk@gmail.com
  twitter_username: ecenur_ozturk
  facebook_username: ecenur
  instagram_username: ecenurozturk
  github_username: ecenurozturk
  linkedin_username: ecenur-öztürk-79b082a1

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
